# Site settings 
title: Alberto Gaona
tagline: Systems computer engineer and AI engineer
description: Blog bla bla bla
baseurl: /blog
url: "https://betogaona7.github.io"

author:
  name: "Alberto Gaona"
  email: "albertoo_3c@hotmail.com"
  instagram: "betogaona7"
  github: "betogaona7"
  linkedin: "betogaona7"
  facebook: "betogaona07"

markdown: kramdown
encoding: UTF-8
future: true

disqus: "https-betogaona7-github-io-blog"
fid: "2010447859198340"

permalink: /:categories/:year/:month/:day/:title
